export const RedflagsActionTypes = {
  FETCH_REDFLAGS_IN_PROGRESS: 'FETCH_REDFLAGS_IN_PROGRESS',
  FETCH_REDFLAGS_SUCCESS: 'FETCH_REDFLAGS_SUCCESS',
  FETCH_REDFLAGS_FAILURE: 'FETCH_REDFLAGS_FAILURE',
  FETCH_A_REDFLAG: 'FETCH_A_REDFLAG',
  REDFLAG_FETCH_NOT_FOUND: 'ARTICLE_FETCH_NOT_FOUND',
  FETCHING_REDFLAG: 'FETCHING_ARTICLE',
};
